services:
  mysql:
    image: mysql:8
    container_name: ecommerce_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'ecommerce'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  redis:
    image: redis:alpine
    container_name: ecommerce_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  ecommerce-dev:
    image: robertoklann/newweb:octane
    container_name: ecommerce-dev
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
      args:
        PHP_VERSION: '8.2.4-bullseye'
    ports:
      - "80:80"       # http
      - "443:443"     # https
      - "8000:8000"   # octane
      - "5173:5173"   #vite
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
  redis_data:
